export const REASON_CODES = {
  PURPOSE_VALID: 'PURPOSE_VALID',
  PURPOSE_MISMATCH: 'PURPOSE_MISMATCH',
  VERIFIER_PATTERN_MATCHED: 'VERIFIER_PATTERN_MATCHED',
  VERIFIER_PATTERN_MISMATCH: 'VERIFIER_PATTERN_MISMATCH',
  RAW_ATTRIBUTE_NOT_PROPORTIONAL: 'RAW_ATTRIBUTE_NOT_PROPORTIONAL',
  MINIMAL_DISCLOSURE_REQUIRED: 'MINIMAL_DISCLOSURE_REQUIRED',
  USER_CONSENT_REQUIRED: 'USER_CONSENT_REQUIRED',
  PRESENCE_REQUIRED: 'PRESENCE_REQUIRED',
  NONCE_REQUIRED: 'NONCE_REQUIRED',
  AUDIENCE_BINDING_REQUIRED: 'AUDIENCE_BINDING_REQUIRED',
  NO_ALLOWED_DISCLOSURE_PATH: 'NO_ALLOWED_DISCLOSURE_PATH',
  FAIL_CLOSED: 'FAIL_CLOSED',
} as const;

export type PolicyReasonCode = (typeof REASON_CODES)[keyof typeof REASON_CODES];
