/**
 * Audit Log Type Definitions
 * Defines what events are logged and how they form a hash chain
 */

import { DID, URI } from './vc';

/**
 * Types of auditable events in the miTch system
 */
export type AuditEventType =
    | 'KEY_CREATED'          // Ephemeral key generated
    | 'KEY_USED'             // Key used for operation
    | 'KEY_DESTROYED'        // Key shredded (crypto-shredding)
    | 'VC_IMPORTED'          // Credential received from issuer
    | 'VC_DELETED'           // Credential removed
    | 'VP_GENERATED'         // Presentation created
    | 'VP_SENT'              // Presentation sent to verifier
    | 'POLICY_EVALUATED'     // Policy check performed
    | 'POLICY_BLOCKED'       // Request blocked by policy
    | 'USER_CONSENT_GRANTED' // User approved credential sharing
    | 'USER_CONSENT_DENIED'; // User denied credential sharing

/**
 * Audit log entry with hash chain
 * Forms an immutable, verifiable log
 */
export interface AuditLogEntry {
    /**
     * Unique identifier for this entry
     */
    id: string;

    /**
     * ISO 8601 timestamp of event
     */
    timestamp: string;

    /**
     * Type of event
     */
    action: AuditEventType;

    /**
     * Optional identifier of subject (e.g., credential ID, key ID)
     * Should be pseudonymous or hashed if sensitive
     */
    subjectId?: string;

    /**
     * Optional verifier DID (for presentation events)
     */
    verifierId?: DID;

    /**
     * SHA-256 hash of previous log entry
     * Forms the chain linking
     */
    previousHash: string;

    /**
     * SHA-256 hash of this entry
     * Computed as: Hash(timestamp + action + subjectId + previousHash + metadata)
     */
    currentHash: string;

    /**
     * Cryptographic signature of currentHash by the wallet's internal Audit Key
     * Proves that the entry was generated by the authentic wallet software.
     */
    signature?: string;

    /**
     * Algorithm used for signing (e.g. 'ECDSA_P256_SHA256')
     */
    sigAlg?: string;

    /**
     * Key Identifier used for signing (Truth Anchor ID)
     */
    kid?: string;

    /**
     * Version of the entry schema
     */
    version?: string;

    /**
     * Optional additional metadata (hashed, not raw data)
     */
    metadata?: Record<string, unknown>;
}

/**
 * Audit log export structure
 * Used for GDPR "right to data portability"
 */
export interface AuditLogExport {
    /**
     * Version of export format
     */
    version: string;

    /**
     * When this export was created
     */
    exportedAt: string; // ISO 8601

    /**
     * DID of the user whose log this is
     */
    owner: DID;

    /**
     * All log entries
     */
    entries: AuditLogEntry[];

    /**
     * Verification result
     */
    chainIntegrity: {
        valid: boolean;
        brokenAtIndex?: number;
    };

    /**
     * SHA-256 hash of the entire entries array (canonical)
     */
    reportHash: string;

    /**
     * Optional compliance summary for auditors
     */
    complianceSummary?: {
        totalEvents: number;
        shreddingCount: number;
        dataMinimizationEvents: number;
        averageShreddingLatencyMs: number;
        policyComplianceStatus: 'EXCELLENT' | 'GOOD' | 'ATTENTION';
    };

    /**
     * Optional cryptographic anchors on Layer 2
     */
    anchors?: L2AnchorReceipt[];

    /**
     * Cryptographic signature of reportHash
     */
    signature?: string;
}

/**
 * Proof of state placement on a Distributed Ledger (L2)
 */
export interface L2AnchorReceipt {
    stateRoot: string;
    l2TransactionId: string;
    blockHeight: number;
    timestamp: string;
    network: string;
    /**
     * Status of the anchor transaction
     * - 'pending': Queued for batching
     * - 'confirmed': Successfully anchored on L2
     * - 'failed': Anchoring failed
     */
    status?: 'pending' | 'confirmed' | 'failed';
}


/**
 * Crypto-shredding event metadata
 * Specific to key destruction events
 */
export interface ShreddingEventMetadata {
    /**
     * Type of key that was shredded
     */
    keyType: 'ephemeral' | 'session' | 'presentation';

    /**
     * How long the key existed (in milliseconds)
     */
    keyLifetimeMs: number;

    /**
     * What the key was used for
     */
    purpose: string;

    /**
     * Verification that shredding was successful
     */
    shreddingVerified: boolean;
}

/**
 * Presentation event metadata
 */
export interface PresentationEventMetadata {
    /**
     * Which credential types were presented
     */
    credentialTypes: string[];

    /**
     * Which claims were shared
     */
    claimsShared: string[];

    /**
     * Whether Zero-Knowledge Proof was used
     */
    usedZKP: boolean;

    /**
     * Policy decision that allowed this
     */
    policyDecision: 'ALLOW' | 'WARN';
}
