import type { DID } from './vc.js';

/**
 * Anonymous Verifier Reputation Report
 *
 * Generated by the miTch Wallet 'Sensor' when interacting with a Verifier.
 * Contains no user identifiers.
 */
export interface VerifierReportCard {
  /**
   * Target verifier identification (DID or Domain)
   */
  verifierId: DID | string;

  /**
   * Timestamp of the interaction
   */
  timestamp: string;

  /**
   * Metrics regarding the request quality
   */
  metrics: {
    /** Number of claims requested */
    claimsRequestedCount: number;
    /** Was Zero-Knowledge Proof (ZKP) accepted? */
    zkpAccepted: boolean;
    /** Number of third-party trackers detected on the origin */
    trackerCount: number;
    /** Does the verifier have a valid TSL (Trust Service List) entry? */
    isTrustedIssuer?: boolean;
    /** Did the verifier request 'over-disclosure' (e.g. DOB for age)? */
    overRequestingDetected: boolean;
  };

  /**
   * Security score calculated by the local wallet (0.0 to 1.0)
   */
  localPrivacyScore: number;

  /**
   * Optional user-provided rating (0-5 stars)
   */
  userRating?: number;

  /**
   * Cryptographic proof that this report was generated by a valid miTch wallet
   * (e.g. a collective blind signature or simply a hardware-bound key signature)
   */
  proof?: {
    signature: string;
    alg: string;
    kid: string;
  };
}

/**
 * Public Verifier Rating (Aggregated)
 */
export interface VerifierGlobalReputation {
  verifierId: string;
  globalPrivacyScore: number; // 0.0 to 1.0
  totalReports: number;
  lastUpdated: string;
  badges: ('DATA_GLUTTON' | 'PRIVACY_CHAMPION' | 'OVER_REQUESTER' | 'TRUSTED')[];
}
